networks:
  front:
    external: false
  back:
    external: false

services: 
  web:
    image: nginx
    volumes: 
      - ./index.html:/usr/share/nginx/html/index.html
      - ./src:/usr/share/nginx/html/src
    ports:
      - 80:80
    networks:
      - front

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
    networks:
      - front
      - back
  
  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=dan
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - back


    